## *********************************************************
##
## File autogenerated for the gem_integration_tests package
## by the dynamic_reconfigure package.
## Please do not edit.
##
## ********************************************************/

from dynamic_reconfigure.encoding import extract_params

inf = float('inf')

config_description = {'name': 'Default', 'type': '', 'state': True, 'cstate': 'true', 'id': 0, 'parent': 0, 'parameters': [{'name': 'estop_enabled', 'type': 'bool', 'default': False, 'level': 0, 'description': 'Estop enabled', 'min': False, 'max': True, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'bool', 'cconsttype': 'const bool'}, {'name': 'battery_level', 'type': 'int', 'default': 80, 'level': 0, 'description': 'Battery Level (%)', 'min': 0, 'max': 100, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'gps_accuracy', 'type': 'double', 'default': 100.0, 'level': 0, 'description': 'GPS Accuracy (mm)', 'min': 0.0, 'max': 300.0, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}, {'name': 'signal_strength', 'type': 'int', 'default': 0, 'level': 1, 'description': 'Network Status', 'min': 2, 'max': 2147483647, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'int', 'cconsttype': 'const int'}, {'name': 'temperature', 'type': 'double', 'default': 30.0, 'level': 0, 'description': 'Temperature (deg C)', 'min': 0.0, 'max': 100.0, 'srcline': 272, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'edit_method': '', 'ctype': 'double', 'cconsttype': 'const double'}], 'groups': [], 'srcline': 244, 'srcfile': '/opt/ros/noetic/lib/python3/dist-packages/dynamic_reconfigure/parameter_generator.py', 'class': 'DEFAULT', 'parentclass': '', 'parentname': 'Default', 'field': 'default', 'upper': 'DEFAULT', 'lower': 'groups'}

min = {}
max = {}
defaults = {}
level = {}
type = {}
all_level = 0

#def extract_params(config):
#    params = []
#    params.extend(config['parameters'])
#    for group in config['groups']:
#        params.extend(extract_params(group))
#    return params

for param in extract_params(config_description):
    min[param['name']] = param['min']
    max[param['name']] = param['max']
    defaults[param['name']] = param['default']
    level[param['name']] = param['level']
    type[param['name']] = param['type']
    all_level = all_level | param['level']

